### ISSUE TITLE
[FRQ] Add methods for changing "self" profile data (pushName, status message, picture)

### ISSUE THREAD

**Issue by sandro-salles** [HanzHaxors/fabuya#12]
In first place, great work! I'm following what you're doing here and i think it's amazing... hope to colaborate with as well (I'll probably try to create a redis storage for auth credentials and message store, as soon as its finished i'll send a PR)

**Is your feature request related to a problem? Please describe.**
Right now there is no method to set profile basic data (pushName, status message and profile picture).

**Describe the solution you'd like**
It would be very nice to have that!

**Comment by HanzCEO** [comment]
Hey thank you for your interest!

I will investigate how to do this

**Comment by HanzCEO** [comment]
About your message store, could you make another issue for that? Appreciate that

**Comment by HanzCEO** [comment]
- [x] Changing profile picture
```js
client.setProfilePicture(fs.readFileSync(...))
client.getProfilePicture() // => url to picture
```
 - [x] Changing push name
```js
client.setPushName("My new pushName")
```
 - [x] Changing bio (aka status)
```js
client.setBio("My Bio")
```

These are available on `fabuya@nightly`.

**Comment by HanzCEO** [comment]
Thank you for your interest, I appreciate that very much!
