### ISSUE TITLE
[BUG] Error installing from git

### ISSUE THREAD

**Issue by MacKey-255** [HanzHaxors/fabuya#13]
Hello, when I install Fabuya using: `yarn add git+https://github.com/HanzHaxors/fabuya.git` and using it.
Error: `Cannot find module './baileys-lib'` in `'node_modules/fabuya/index.js'`
SAlu2s

**Comment by HanzCEO** [comment]
Well, i haven't made the workflow for installing via source. I will fix this

**Comment by HanzCEO** [comment]
Hello, i recently commit the solution. Tell me in case something went wrong.
